picolog:
  base_url: "https://api.picolog.app/v1/"
  api_key: "kQRwCX2OBNPTjTb6qyS-bSvPhcKs7GIPebT4Fr61u871c"
  device_id: "9c6adba8-2880-45ad-b62b-5f3ee028969b"

influxdb:
  url: "https://us-east-1-1.aws.cloud2.influxdata.com"
  token: "sNd_jKNKcjGXPhUmwC9tJlyGrA3y__I3FN5SSaHnFyLJMh7g5UeJFnaSaR-ltm8XUjBdxMWc4H_uaQX8Crv2Yg=="
  org: "project"
  bucket: "picolog"

scheduler:
  interval_minutes: 5
