picolog:
  base_url: "https://api.picolog.app/v1/"
  api_key: <API_KEY>
  device_id: <DEVICE_ID>
influxdb:
  url: "https://us-east-1-1.aws.cloud2.influxdata.com"
  token: <TOKEN>
  org: "project"
  bucket: "picolog"

scheduler:
  interval_minutes: 5
